
[build]
  command = "npm install && npm run build"
  publish = "out"
  functions = "netlify/functions"  # Solo se usi serverless functions

[build.environment]
  NODE_VERSION = "18.19.1"  # Versione specifica
