[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"

[build.environment]
  NODE_OPTIONS = "--max_old_space_size=4096"
