[build]
  command = "npm ci --legacy-peer-deps && npm run build && npm run export"
  publish = "out"

[build.environment]
  NODE_VERSION = "18.19.1"
  NODE_OPTIONS = "--max_old_space_size=4096"
  CI = "true"  # Obbligatorio per npm ci
